
stages:
    - build
    - test
test:
  stage: test
  script:
  - echo nuget download...
  - '"C:\Progra~2\MSBuild\14.0\Bin\nuget" restore "QualityCaps.sln"'
  - echo msbuild
  - 'C:\Progra~2\MSBuild\14.0\Bin\msbuild.exe QualityCaps.sln /p:Configuration=Release'
  - echo testing...
  - dir /s /b *.Test*.dll | findstr /r .Test*\\*\\bin\\ > testcontainers.txt
  - 'for /f %%f in (testcontainers.txt) do "%MsTestPath%mstest.exe" /testcontainer:"%%f"'
  except:
  - tags